name: Release

on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      term: xterm
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
        node-version:
          - 24

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - name: Install Bun
        uses: tanaabased/actions/setup-bun@v1

      - name: Install node ${{ matrix.node-version }}
        uses: tanaabased/actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: bun install --no-save --frozen-lockfile

      - name: Publish repository
        uses: tanaabased/actions/publish-repo@v1
        with:
          sync-token: ${{ secrets.TANAAB_COAXIUM_INJECTOR }}
      - name: Pack prepared package
        id: package
        uses: tanaabased/actions/npm-pack@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Publish package to npm
        uses: tanaabased/actions/publish-npm@v1
        with:
          tarball: ${{ steps.package.outputs.tarball-path }}
          registry-token: ${{ secrets.TANAAB_NPM_DEPLOY }}
          channel-token: ${{ secrets.TANAAB_NPM_DEPLOY }}
          node-version: ${{ matrix.node-version }}
          stable-tag: latest
          prerelease-tag: edge
          update-prerelease-tag-on-stable: true
